server:
  forward-headers-strategy: framework
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        # Swagger UI Routes
        - id: auth-swagger
          uri: lb://AUTH-USER-SERVICE
          predicates:
            - Path=/nestjs-user-auth/swagger/**
        - id: order-swagger
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/2025/order-service/swagger/**
        - id: event-swagger
          uri: lb://EVENT-TICKET-SERVICE
          predicates:
            - Path=/event-ticket-service/swagger/**
          filters:
            - RewritePath=/event-ticket-service/swagger/(?<segment>.*), /swagger/${segment}
        # Application Routes
        - id: event-route
          uri: lb://EVENT-TICKET-SERVICE
          predicates:
            - Path=/api/v1/2025/events/**
        - id: category-route
          uri: lb://EVENT-TICKET-SERVICE
          predicates:
            - Path=/api/v1/2025/categories/**
        - id: ticket-route
          uri: lb://EVENT-TICKET-SERVICE
          predicates:
            - Path=/api/v1/2025/tickets/**
        - id: event-times-route
          uri: lb://EVENT-TICKET-SERVICE
          predicates:
            - Path=/api/v1/2025/eventTimes/**
        - id: auth-route
          uri: lb://AUTH-USER-SERVICE
          predicates:
            - Path=/api/v1/2025/auth/**
        - id: orders-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/2025/orders/**
        - id: orders-route-admin
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/2025/admins/orders/**
        - id: orders-route-user
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/2025/users/orders/**
        - id: users-route
          uri: lb://AUTH-USER-SERVICE
          predicates:
            - Path=/api/v1/2025/users/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth User Service
        url: /nestjs-user-auth/swagger/json
      - name: Order Service
        url: /api/v1/2025/order-service/swagger/json
      - name: Event Ticket Service
        url: /event-ticket-service/swagger/doc.json
     
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
